version: '3.9'

services:
 
  backend:
    container_name: backend
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3000:3000
    restart: always 
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - /app/src
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?schema=public
    networks:
      - backend-network
      - db-network 
  db:
    container_name: db
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}", "-p", "${POSTGRES_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
    networks:
      - db-network

networks:
  backend-network:
    driver: bridge 
  db-network:
    driver: bridge  
